name: Go Build and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Create Env File
      run: |
        echo "$secret" > .env
        rm -f .gitignore
      env:
        secret: ${{ secrets.env }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
